name:  Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setip Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Check Cache
        uses: actions/cache@v3
        id: cache-node-module
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        if: steps.cache.output.cache-hit != 'true'
        run: npm ci
      - name: Build and Deploy
        run: |
          npm run build
          mkdir deploy
          git worktree add ../deploy deploy
          cp -r dist/ ../deploy
          cd ../deploy
          git config --global user.name "codingjwp"
          git config --global user.email "codingjwp@github.com"
          git add .
          git commit -m "deploy: new deploy"
          git push origin deploy
